version: 2

jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: install-test-suite
          command: npm install
      - run:
          name: test
          command: npm test